Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,11 +28,38 @@ jobs:
       - name: checkout
         uses: actions/checkout@v4
 
-      - name: godot-tester
+      - name: Download Godot
+        run: |
+          curl -L https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip -o godot.zip
+          ls -lh godot.zip
+          unzip -l godot.zip
+
+      - name: Unzip Godot
+        run: |
+          unzip godot.zip -d godot
+          ls -lh godot
+
+      - name: Verify Godot executable
+        run: |
+          if [ ! -f godot/Godot_v4.3-stable_linux.x86_64 ]; then
+            echo "Godot executable not found!"
+            exit 1
+          else
+            echo "Godot executable found."
+          fi
+
+      - name: Install Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y unzip wget
+
+      - name: Run godot-tester
         uses: croconut/godot-tester@v5.1
-        with: 
+        with:
           version: 4.3
           custom-godot-dl-url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
+          godot_executable: godot/Godot_v4.3-stable_linux.x86_64
+          # Additional inputs as needed for your testing
           
 
       - name: export game
